### ISSUE TITLE
Microsoft Office Dokumente mit Dynamic Data Exchange (DDE) Felder

### ISSUE THREAD

**Issue by svengo** [jamct/protector#10]
Microsoft hat unter https://technet.microsoft.com/en-us/library/security/4053440 aktuell ein Security Advisory veröffentlicht in dem beschrieben wird, wie sich Office gegen DDE-Attacken härten lässt.

> Microsoft is releasing this security advisory to provide information regarding security settings for Microsoft Office applications. This advisory provides guidance on what users can do to ensure that these applications are properly secured when processing Dynamic Data Exchange (DDE) fields.
> ...
> In an email attack scenario, an attacker could leverage the DDE protocol by sending a specially crafted file to the user and then convincing the user to open the file, typically by way of an enticement in an email. The attacker would have to convince the user to disable Protected Mode and click through one or more additional prompts. As email attachments are a primary method an attacker could use to spread malware, Microsoft strongly recommends that customers exercise caution when opening suspicious file attachments.

Wäre das was für den protector?

**Comment by beerisgood** [comment]
@svengo 
Empfohlene, bessere Lösung als dieses Projekt:
https://github.com/AndyFul/Hard_Configurator

**Comment by svengo** [comment]
> https://github.com/AndyFul/Hard_Configurator

Danke für den Hinweis, @beerisgood!
