### ISSUE TITLE
Projekt tot?

### ISSUE THREAD

**Issue by beerisgood** [jamct/protector#12]
War das wieder nur ein kurzes heise Projekt oder darf man seit September 2017 noch Updates erwarten?

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
Tot

**Comment by ovz93br43v7** [comment]
Würde mich auch interessieren...

**Comment by Un1matr1x** [comment]
@jamct ?

**Comment by beerisgood** [comment]
> @jamct ?

Wird sich keiner melden. Das Tool wurde gebaut um einen Artikel drüber schreiben zu können und das wars.

Als (weitaus bessere) Lösung kann ich euch https://github.com/AndyFul/Hard_Configurator empfehlen.

@ovz93br43v7 @Un1matr1x

**Comment by ovz93br43v7** [comment]
@beerisgood Danke für den Hinweis, bin mittlerweile auf Linux umgestiegen und verwende Windows nur noch wenn es unumgänglich ist (Spiele, Steuerprogramm). Ich kann dir nur empfehlen dich z.B. mit [Pihole](https://github.com/pi-hole) zu beschäftigen das Projekt ist nützlicher weil man damit alle Geräteanfragen blocken kann ohne ständig auf jedem Gerät einzeln zu basteln. (also auch Geräte die man nicht so einfach modifizieren kann --> smart-home z.B.)

**Comment by beerisgood** [comment]
> @beerisgood Danke für den Hinweis, bin mittlerweile auf Linux umgestiegen und verwende Windows nur noch wenn es unumgänglich ist (Spiele, Steuerprogramm).
>

Von Linux kann ich nur abraten. Siehe zB https://madaidans-insecurities.github.io/linux.html
Meine Empfehlung ist iOS / iPadOS. MacOS falls es ein Desktop OS sein muss. Windows 11 wäre die Alternative.

> Ich kann dir nur empfehlen dich z.B. mit [Pihole](https://github.com/pi-hole) zu beschäftigen das Projekt ist nützlicher weil man damit alle Geräteanfragen auf DNS-Ebene blocken kann ohne ständig auf jedem Gerät einzeln zu basteln. (also auch Geräte die man nicht so einfach modifizieren kann --> smart-home z.B.)
>

PiHole hatte ich ein paar Jahre im Einsatz, es schafft aber mehr Probleme als es löst. Ich kann nur Quad9 und NextDNS empfehlen. Und eventuell das kommende Adguard DNS.
