### ISSUE TITLE
Weitere unsichere Dateiendungen blocken

### ISSUE THREAD

**Issue by beerisgood** [jamct/protector#4]
Folgende fehlen:
CMD, BAT, VBE
Bei JSE hat sich scheinbar ein Rechtschreibfehler eingeschlichen, denn in der Beschreibung steht "JES"

![jse](https://user-images.githubusercontent.com/9625159/30659973-ba4c236e-9e3f-11e7-80dc-b6668d425597.png)

**Comment by obsti8383** [comment]
.cmd und .bat abzuschalten erschienen uns bei Hardentools (Security Without Borders: https://github.com/securitywithoutborders/hardentools) als zu gefährlich für die Funktionalität von diversen Anwendungen (werden oft schon als Start-Skript u.ä. eingesetzt).

.vbe abzuschalten dagegen macht sicherlich Sinn.

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
Projekt ist tot.

Empfohlene, bessere Lösung:
https://github.com/AndyFul/Hard_Configurator
