### ISSUE TITLE
Code Signing Certificate has expired

### ISSUE THREAD

**Issue by Ascendor** [jamct/protector#5]
>         Signers:
>            Heise Medien GmbH & Co. KG
>                 Cert Status:    This certificate or one of the certificates in the certificate chain is not time valid.
>                 Valid Usage:    Code Signing
>                 Cert Issuer:    COMODO RSA Code Signing CA
>                 Serial Number:  00 CD DC 88 8F 8D FB 92 59 A4 98 E0 BB 83 91 5E 50
>                 Thumbprint:     70D8F37CD6AFC97C929FA4C0B5F452CB2E622983
>                 Algorithm:      sha256RSA
>                 Valid from:     02:00 16.09.2015
>                 Valid to:       01:59 16.09.2017

**Comment by beerisgood** [comment]
Can confirm that

**Comment by beerisgood** [comment]
Fixed with https://github.com/jamct/protector/releases/tag/1.0.1

Even if it isnt listed in changelog

**Comment by Ascendor** [comment]
Confirmed, 1.0.1 has a valid signature.
