### ISSUE TITLE
Copy Paste von Bildern geht nicht mehr

### ISSUE THREAD

**Issue by thulka** [jamct/protector#9]
auch nicht nach nochmaligem Lauf mit "ACtiveX", "OLE" deaktivieren entfernt.

**Comment by obsti8383** [comment]
Copy/Paste von welcher Anwendung in welche Anwendung geht nicht mehr? Word?

**Comment by thulka** [comment]
Ja genau Word.

Ich glaube allerdings, dass das doch nicht protector zu tun hat. Ich habe dann nämlich ein System Restore gemacht auf die Zeit vor protector und da ging es auch nicht. Komischerweise kann ich vom Browser in Outlook copy/pasten dieselben Bilder werden in Word aber nicht angezeigt, der Cursor bewegt sich nach dem paste, es ist ein Platzhalter im Word aber das Bild nicht. Speichere ich das Bild auf der Festplatte und drag/droppe es ins Word, erscheint das BIld im Word. Mache ich aus dem Browser heraus ein Copy/Paste mit Paste/Special und währe Device-Independant-Bitmap dann erscheint das Bild auch. Vielleicht war das im Word auch schon vor protector.

Also wie gesagt, Protector dürfte eher unschuldig sein. Pardon, Verzeihung, Meine Schuld, [ich entschuldige mich](https://www.youtube.com/watch?v=_mI7ldxcio0). Und vielen Dank für das Tool. NSI Skripter haben all meinen Respekt ;-)

Ein Undo habe ich vermisst, mir scheint hardening geht nur in die eine RIchtung oder?
